<?php

namespace Modules\Student\Actions;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Modules\Identity\Enums\UserStatus;
use Modules\Identity\Models\User;
use Modules\Student\Models\Student;

/**
 * Creates (or safely reuses) the login account belonging to one student.
 *
 * The generated password is exposed once through $generatedPassword so the
 * operator can hand it over; it is never persisted in plain text.
 */
class ProvisionStudentAccountAction
{
    public ?string $generatedPassword = null;

    public const DEFAULT_EMAIL_DOMAIN = 'student.ac.id';

    public function deriveEmail(Student $student): string
    {
        return $student->email ?: $student->student_number . '@' . self::DEFAULT_EMAIL_DOMAIN;
    }

    /**
     * @throws ValidationException when the email belongs to an account this student may not take over
     */
    public function execute(string $email, string $fullName, ?string $password = null, ?Student $student = null): User
    {
        $existing = User::where('email', $email)->first();

        if ($existing) {
            $this->assertCanReuse($existing, $email, $student);
        }

        $autoGenerated = $password === null;
        $this->generatedPassword = $password ?? Str::password(12);

        if ($existing) {
            $existing->update([
                'password' => Hash::make($this->generatedPassword),
                'status' => UserStatus::ACTIVE,
                'must_change_password' => $autoGenerated,
            ]);
            $existing->assignRole('mahasiswa');

            return $existing;
        }

        $user = User::create([
            'name' => $fullName,
            'email' => $email,
            'password' => Hash::make($this->generatedPassword),
            'status' => UserStatus::ACTIVE,
            'must_change_password' => $autoGenerated,
        ]);
        $user->assignRole('mahasiswa');

        return $user;
    }

    private function assertCanReuse(User $user, string $email, ?Student $student): void
    {
        $linkedStudentId = Student::where('user_id', $user->id)->value('id');

        if ($linkedStudentId && $linkedStudentId !== $student?->id) {
            throw ValidationException::withMessages([
                'email' => [
                    "Email {$email} sudah terhubung ke data mahasiswa lain. Perbaiki email mahasiswa ini terlebih dahulu.",
                ],
            ]);
        }

        $foreignRoles = $user->roles()->pluck('name')
            ->reject(fn (string $name) => $name === 'mahasiswa')
            ->values();

        if ($foreignRoles->isNotEmpty()) {
            throw ValidationException::withMessages([
                'email' => [
                    "Email {$email} sudah dipakai akun dengan peran " . $foreignRoles->implode(', ')
                    . '. Gunakan email lain untuk mahasiswa ini.',
                ],
            ]);
        }
    }
}
