export interface RegionHierarchy {
  [province: string]: {
    [city: string]: string[]
  }
}

export const INDONESIA_REGIONS: RegionHierarchy = {
  'Jawa Barat': {
    'Kab. Cirebon': ['Sumber', 'Weru', 'Plered', 'Kedawung', 'Gunungjati', 'Klangenan', 'Palimanan', 'Arjawinangun', 'Panguragan', 'Ciwaringin', 'Susukan', 'Gegesik', 'Kaliwedi', 'Kapetakan', 'Suranenggala', 'Mundu', 'Beber', 'Talun', 'Plumbon', 'Depok', 'Dukupuntang', 'Astanalajang', 'Pabuaran', 'Babakan', 'Waled', 'Ciledug', 'Losari', 'Gebang', 'Karangsembung', 'Lemahabang', 'Sedong', 'Greged', 'Karangwareng'],
    'Kota Cirebon': ['Kejaksan', 'Kesambi', 'Pekalipan', 'Harjamukti', 'Lemahwungkuk'],
    'Kab. Kuningan': ['Kuningan', 'Cigugur', 'Kramatmulya', 'Jalaksana', 'Cilimus', 'Mandirancan', 'Pasawahan', 'Pancalang', 'Ciawigebang', 'Cidahu', 'Kalimanggis', 'Cimahi', 'Luragung', 'Lebakwangi', 'Ciwaru', 'Karangkancana', 'Cibingbin', 'Subang', 'Selajambe', 'Hantara', 'Darma', 'Kadugede', 'Nusaherang', 'Ciniru', 'Garawangi', 'Maleber'],
    'Kab. Majalengka': ['Majalengka', 'Cigasong', 'Sukahaji', 'Sindangwangi', 'Rajagaluh', 'Leuwimunding', 'Palasah', 'Jatiwangi', 'Dawuan', 'Kasokandel', 'Panyingkiran', 'Kadipaten', 'Kertajati', 'Jatitujuh', 'Ligung', 'Sumberjaya', 'Bantarujeg', 'Cikijing', 'Talaga', 'Cingambul', 'Malausma', 'Lemahsugih', 'Argapura', 'Maja', 'Banjaran', 'Sindang'],
    'Kab. Indramayu': ['Indramayu', 'Sindang', 'Pasekan', 'Balongan', 'Juntinyuat', 'Karangampel', 'Kedokan Bunder', 'Krangkeng', 'Sliyeg', 'Jatibarang', 'Widasari', 'Kertasemaya', 'Sukagumiwang', 'Tukdana', 'Bangodua', 'Lelea', 'Cikedung', 'Terisi', 'Losarang', 'Kandanghaur', 'Cantigi', 'Arahan', 'Lohbener', 'Gabuswetan', 'Kroya', 'Gantar', 'Haurgeulis', 'Anjatan', 'Sukra', 'Patrol'],
    'Kota Bandung': ['Coblong', 'Sukajadi', 'Cicendo', 'Andir', 'Astanaanyar', 'Regol', 'Lengkong', 'Batununggal', 'Kiaracondong', 'Arcamanik', 'Antapani', 'Ujungberung', 'Cibiru', 'Buahbatu', 'Bandung Wetan', 'Sumur Bandung'],
    'Kab. Bandung': ['Soreang', 'Margahayu', 'Katapang', 'Banjaran', 'Ciparay', 'Majalaya', 'Baleendah', 'Dayeuhkolot', 'Bojongsoang', 'Rancaekek', 'Cileunyi', 'Cimenyan'],
    'Kab. Bandung Barat': ['Padalarang', 'Ngamprah', 'Lembang', 'Parongpong', 'Cisarua', 'Batujajar', 'Cililin', 'Cipatat'],
    'Kota Bekasi': ['Bekasi Barat', 'Bekasi Timur', 'Bekasi Utara', 'Bekasi Selatan', 'Rawalumbu', 'Medansatria', 'Pondokgede', 'Jatiasih'],
    'Kab. Bekasi': ['Cikarang Pusat', 'Cikarang Barat', 'Cikarang Timur', 'Cikarang Utara', 'Cikarang Selatan', 'Tambun Selatan', 'Tambun Utara', 'Cibitung'],
    'Kota Bogor': ['Bogor Tengah', 'Bogor Barat', 'Bogor Timur', 'Bogor Selatan', 'Bogor Utara', 'Tanah Sareal'],
    'Kab. Bogor': ['Cibinong', 'Ciawi', 'Cisarua', 'Megamendung', 'Babakan Madang', 'Citeureup', 'Gunung Putri', 'Cileungsi', 'Jonggol', 'Parung', 'Kemang', 'Dramaga', 'Ciampea', 'Leuwiliang'],
    'Kota Depok': ['Pancoran Mas', 'Sukmajaya', 'Beji', 'Cimanggis', 'Sawangan', 'Limo', 'Cinere', 'Tapos', 'Cilodong', 'Bojongsari'],
    'Kota Tasikmalaya': ['Cihideung', 'Cipedes', 'Tawang', 'Indihiang', 'Kawalu', 'Tamansari', 'Mangkubumi', 'Bungursari', 'Purbaratu'],
    'Kab. Tasikmalaya': ['Singaparna', 'Leuwisari', 'Padakembang', 'Sukarame', 'Manonjaya', 'Cineam', 'Karangnunggal', 'Cipatujah'],
    'Kab. Garut': ['Garut Kota', 'Tarogong Kidul', 'Tarogong Kaler', 'Samarang', 'Bayongbong', 'Cikajang', 'Kadungora', 'Leles', 'Cibatu'],
    'Kab. Ciamis': ['Ciamis', 'Baregbeg', 'Cikoneng', 'Sadananya', 'Kawali', 'Panawangan', 'Rancah', 'Pamarican'],
    'Kab. Pangandaran': ['Parigi', 'Pangandaran', 'Sidamulih', 'Kalipucang', 'Padaherang', 'Cijulang', 'Cimerak', 'Cigugur', 'Langkaplancar'],
    'Kota Banjar': ['Banjar', 'Pataruman', 'Purwaharja', 'Langensari'],
    'Kab. Subang': ['Subang', 'Kalijati', 'Pagaden', 'Pabuaran', 'Ciasem', 'Pamanukan', 'Pusakajaya', 'Jalan Cagak', 'Ciater'],
    'Kab. Purwakarta': ['Purwakarta', 'Campaka', 'Bungursari', 'Pasawahan', 'Plered', 'Sukatani', 'Darangdan', 'Wanayasa', 'Jatiluhur'],
    'Kab. Karawang': ['Karawang Barat', 'Karawang Timur', 'Telukjambe Timur', 'Telukjambe Barat', 'Klari', 'Rengasdengklok', 'Cikampek', 'Jatisari'],
    'Kota Sukabumi': ['Cikole', 'Citamiang', 'Warudoyong', 'Baros', 'Lembursitu', 'Cibeureum', 'Gunungpuyuh'],
    'Kab. Sukabumi': ['Palabuhanratu', 'Cisaat', 'Cibadak', 'Cicurug', 'Parungkuda', 'Cicurug', 'Surade', 'Jampang Kulon'],
    'Kota Cimahi': ['Cimahi Utara', 'Cimahi Tengah', 'Cimahi Selatan'],
  },
  'Jawa Tengah': {
    'Kota Semarang': ['Semarang Tengah', 'Semarang Barat', 'Semarang Timur', 'Semarang Selatan', 'Semarang Utara', 'Candisari', 'Gajahmungkur', 'Gayamsari', 'Genuk', 'Pedurungan', 'Banyumanik', 'Tembalang', 'Ngaliyan', 'Mijen', 'Gunungpati', 'Tugu'],
    'Kab. Semarang': ['Ungaran Barat', 'Ungaran Timur', 'Ambarawa', 'Bawen', 'Beragas', 'Tuntang', 'Banyubiru', 'Sumowono'],
    'Kota Surakarta (Solo)': ['Banjarsari', 'Jebres', 'Laweyan', 'Pasar Kliwon', 'Serengan'],
    'Kab. Banyumas': ['Purwokerto Timur', 'Purwokerto Barat', 'Purwokerto Utara', 'Purwokerto Selatan', 'Sokaraja', 'Baturraden', 'Ajibarang', 'Wangon', 'Sumpiuh'],
    'Kab. Cilacap': ['Cilacap Selatan', 'Cilacap Tengah', 'Cilacap Utara', 'Kesugihan', 'Kroya', 'Maos', 'Majenang', 'Sidareja'],
    'Kab. Brebes': ['Brebes', 'Jatibarang', 'Wanasari', 'Bulakamba', 'Tanjung', 'Losari', 'Banjarharjo', 'Ketanggungan', 'Larangan', 'Bumiayu', 'Paguyangan', 'Sirampog', 'Tonjong', 'Salem', 'Bantarkawung'],
    'Kota Tegal': ['Tegal Barat', 'Tegal Timur', 'Tegal Selatan', 'Margadana'],
    'Kab. Tegal': ['Slawi', 'Adiwerna', 'Dukuhturi', 'Talang', 'Tarub', 'Pangkah', 'Kramat', 'Suradadi', 'Warureja', 'Lebaksiu', 'Balapulang', 'Bumijawa', 'Bojong'],
    'Kota Pekalongan': ['Pekalongan Barat', 'Pekalongan Timur', 'Pekalongan Utara', 'Pekalongan Selatan'],
    'Kab. Pekalongan': ['Kajen', 'Kedungwuni', 'Wiradesa', 'Wonopringgo', 'Bojong', 'Sragi', 'Doro', 'Karanganyar'],
    'Kab. Pemalang': ['Pemalang', 'Taman', 'Petarukan', 'Comal', 'Ulujami', 'Bantarbolang', 'Randudongkal', 'Moga', 'Belik'],
    'Kab. Kudus': ['Kota Kudus', 'Jati', 'Undaan', 'Mejobo', 'Jekulo', 'Bae', 'Gebog', 'Dawe', 'Kaliwungu'],
    'Kab. Pati': ['Pati', 'Margorejo', 'Gabus', 'Juwana', 'Wedarijaksa', 'Trangkil', 'Tayu', 'Kayen', 'Sukolilo'],
    'Kota Magelang': ['Magelang Utara', 'Magelang Tengah', 'Magelang Selatan'],
    'Kab. Magelang': ['Mertoyudan', 'Mungkid', 'Borobudur', 'Muntilan', 'Salam', 'Salaman', 'Secang', 'Tegalrejo', 'Grabag'],
    'Kab. Kebumen': ['Kebumen', 'Pejagoan', 'Alian', 'Klirong', 'Petanahan', 'Gombong', 'Karanganyar', 'Prembun', 'Kutowinangun'],
  },
  'DKI Jakarta': {
    'Jakarta Pusat': ['Gambir', 'Tanah Abang', 'Menteng', 'Senen', 'Cempaka Putih', 'Johar Baru', 'Kemayoran', 'Sawah Besar'],
    'Jakarta Selatan': ['Kebayoran Baru', 'Kebayoran Lama', 'Pesanggrahan', 'Cilandak', 'Pasar Minggu', 'Jagakarsa', 'Mampang Prapatan', 'Pancoran', 'Tebet', 'Setiabudi'],
    'Jakarta Timur': ['Matraman', 'Pulo Gadung', 'Jatinegara', 'Duren Sawit', 'Kramat Jati', 'Makasar', 'Pasar Rebo', 'Ciracas', 'Cipayung', 'Cakung'],
    'Jakarta Barat': ['Cengkareng', 'Grogol Petamburan', 'Taman Sari', 'Tambora', 'Kebon Jeruk', 'Kalideres', 'Palmerah', 'Kembangan'],
    'Jakarta Utara': ['Koja', 'Kelapa Gading', 'Tanjung Priok', 'Pademangan', 'Penjaringan', 'Cilincing'],
    'Kepulauan Seribu': ['Kepulauan Seribu Utara', 'Kepulauan Seribu Selatan'],
  },
  'Banten': {
    'Kota Tangerang': ['Tangerang', 'Cipondoh', 'Ciledug', 'Karawaci', 'Batuceper', 'Benda', 'Jatiuwung', 'Periuk', 'Pinang', 'Larangan'],
    'Kota Tangerang Selatan': ['Serpong', 'Serpong Utara', 'Pondok Aren', 'Ciputat', 'Ciputat Timur', 'Pamulang', 'Setu'],
    'Kab. Tangerang': ['Tigaraksa', 'Balaraja', 'Cikupa', 'Curug', 'Kelapa Dua', 'Legok', 'Pagedangan', 'Pasar Kemis', 'Sepatan', 'Teluknaga'],
    'Kota Serang': ['Serang', 'Cipocok Jaya', 'Curug', 'Kasemen', 'Taktakan', 'Walantaka'],
    'Kab. Serang': ['Ciruas', 'Kragilan', 'Cikande', 'Kramatwatu', 'Anyar', 'Cinangka', 'Baros', 'Petir'],
    'Kota Cilegon': ['Cilegon', 'Cibeber', 'Citangkil', 'Ciwandan', 'Gerogol', 'Jombang', 'Pulomerak', 'Purwakarta'],
    'Kab. Lebak': ['Rangkasbitung', 'Cibadak', 'Maja', 'Warunggunung', 'Kalanganyar', 'Bayah', 'Malingping'],
    'Kab. Pandeglang': ['Pandeglang', 'Majasari', 'Cadasari', 'Karang Tanjung', 'Labuan', 'Menes', 'Panimbang'],
  },
  'DI Yogyakarta': {
    'Kota Yogyakarta': ['Danurejan', 'Gedongtengen', 'Gondokusuman', 'Gondomanan', 'Jetis', 'Kotagede', 'Kraton', 'Mantrijeron', 'Mergangsan', 'Ngampilan', 'Pakualaman', 'Tegalrejo', 'Umbulharjo', 'Wirobrajan'],
    'Kab. Sleman': ['Depok', 'Mlati', 'Gamping', 'Ngaglik', 'Sleman', 'Kalasan', 'Berbah', 'Prambanan', 'Tempel', 'Turi', 'Pakem', 'Cangkringan'],
    'Kab. Bantul': ['Bantul', 'Sewon', 'Kasihan', 'Banguntapan', 'Piyungan', 'Pleret', 'Imogiri', 'Kretek', 'Sanden', 'Srandakan', 'Pandak', 'Pajangan', 'Sedayu'],
    'Kab. Kulon Progo': ['Wates', 'Pengasih', 'Sentolo', 'Temon', 'Panjatan', 'Galur', 'Lendah', 'Nanggulan', 'Kalibawang', 'Samigaluh', 'Girimulyo', 'Kokap'],
    'Kab. Gunungkidul': ['Wonosari', 'Playen', 'Patuk', 'Paliyan', 'Semanu', 'Karangmojo', 'Ponjong', 'Rongkop', 'Semanu', 'Tepus', 'Tanjungsari', 'Panggang', 'Purwosari'],
  },
  'Jawa Timur': {
    'Kota Surabaya': ['Wonokromo', 'Tegalsari', 'Genteng', 'Bubutan', 'Simokerto', 'Pabean Cantian', 'Semampir', 'Krembangan', 'Rungkut', 'Wonocolo', 'Gubeng', 'Sukolilo', 'Tambaksari', 'Mulyorejo', 'Sawahan', 'Tandes', 'Karangpilang', 'Dukuh Pakis', 'Gayungan', 'Jambangan', 'Wiyung', 'Sambikerep', 'Lakarsantri', 'Pakal', 'Benowo', 'Asemrowo', 'Sukomanunggal', 'Kenjeran', 'Bulak', 'Gunung Anyar'],
    'Kota Malang': ['Klojen', 'Blimbing', 'Kedungkandang', 'Lowokwaru', 'Sukun'],
    'Kab. Malang': ['Kepanjen', 'Singosari', 'Lawang', 'Pakis', 'Dau', 'Karangploso', 'Turen', 'Gondanglegi', 'Dampit'],
    'Kota Batu': ['Batu', 'Bumiaji', 'Junrejo'],
    'Kab. Sidoarjo': ['Sidoarjo', 'Buduran', 'Candi', 'Porong', 'Krembung', 'Tulangan', 'Tanggulangin', 'Waru', 'Gedangan', 'Sedati', 'Taman', 'Krian', 'Sukodono'],
    'Kab. Gresik': ['Gresik', 'Kebomas', 'Manyar', 'Driyorejo', 'Menganti', 'Cerme', 'Benjeng', 'Balongpanggang', 'Bungah', 'Sidayu', 'Dukun', 'Panceng', 'Ujungpangkah', 'Sangkapura', 'Tambak'],
    'Kab. Pasuruan': ['Bangil', 'Pandaan', 'Gempol', 'Sukorejo', 'Prigen', 'Purwosari', 'Purwodadi', 'Kraton', 'Grati'],
    'Kota Pasuruan': ['Panggungrejo', 'Purworejo', 'Bugul Kidul', 'Gadingrejo'],
    'Kota Kediri': ['Kota', 'Mojoroto', 'Pesantren'],
    'Kab. Kediri': ['Pare', 'Gampengrejo', 'Ngasem', 'Gurah', 'Wates', 'Kandangan', 'Papar', 'Plemahan'],
    'Kab. Jombang': ['Jombang', 'Peterongan', 'Tembelang', 'Ploso', 'Mojoagung', 'Mojowarno', 'Diwek', 'Gudo'],
    'Kab. Mojokerto': ['Mojosari', 'Puri', 'Sooko', 'Trowulan', 'Dlanggu', 'Pacet', 'Trawas', 'Ngoro'],
    'Kota Mojokerto': ['Magersari', 'Prajurit Kulon', 'Krangan'],
    'Kab. Banyuwangi': ['Banyuwangi', 'Rogojampi', 'Genteng', 'Glenmore', 'Kalibaru', 'Muncar', 'Cluring', 'Gambiran', 'Kabat'],
    'Kab. Jember': ['Kaliwates', 'Patrang', 'Sumbersari', 'Ajung', 'Rambipuji', 'Balung', 'Ambulu', 'Tanggul'],
  },
  'Sumatera Utara': {
    'Kota Medan': ['Medan Kota', 'Medan Baru', 'Medan Barat', 'Medan Timur', 'Medan Utara', 'Medan Selayang', 'Medan Sunggal', 'Medan Helvetia', 'Medan Petisah', 'Medan Denai', 'Medan Area', 'Medan Johor', 'Medan Amplas', 'Medan Tembung'],
    'Kab. Deli Serdang': ['Lubuk Pakam', 'Percut Sei Tuan', 'Sunggal', 'Deli Tua', 'Pancur Batu', 'Tanjung Morawa'],
  },
  'Sumatera Barat': {
    'Kota Padang': ['Padang Barat', 'Padang Timur', 'Padang Selatan', 'Padang Utara', 'Koto Tangah', 'Kuranji', 'Lubuk Begalung', 'Lubuk Kilangan', 'Nanggalo', 'Pauh', 'Bungus Teluk Kabung'],
    'Kota Bukittinggi': ['Guguk Panjang', 'Mandiangin Koto Selayan', 'Aur Birugo Tigo Baleh'],
  },
  'Riau': {
    'Kota Pekanbaru': ['Sukajadi', 'Senapelan', 'Pekanbaru Kota', 'Rumbai', 'Bukit Raya', 'Tampang', 'Marpoyan Damai', 'Payung Sekaki'],
    'Kota Dumai': ['Dumai Barat', 'Dumai Timur', 'Dumai Kota', 'Dumai Selatan', 'Bukit Kapur', 'Sungai Sembilan', 'Medang Kampai'],
  },
  'Sumatera Selatan': {
    'Kota Palembang': ['Ilir Timur I', 'Ilir Timur II', 'Ilir Barat I', 'Ilir Barat II', 'Seberang Ulu I', 'Seberang Ulu II', 'Sukarami', 'Sako', 'Kemuning', 'Kalidoni', 'Alang-Alang Lebar', 'Plaju', 'Kertapati'],
  },
  'Lampung': {
    'Kota Bandar Lampung': ['Tanjung Karang Pusat', 'Tanjung Karang Barat', 'Tanjung Karang Timur', 'Kedaton', 'Rajabasa', 'Sukarame', 'Way Halim', 'Teluk Betung Selatan', 'Teluk Betung Barat', 'Teluk Betung Utara'],
    'Kota Metro': ['Metro Pusat', 'Metro Barat', 'Metro Timur', 'Metro Selatan', 'Metro Utara'],
  },
  'Bali': {
    'Kota Denpasar': ['Denpasar Barat', 'Denpasar Timur', 'Denpasar Selatan', 'Denpasar Utara'],
    'Kab. Badung': ['Kuta', 'Kuta Selatan', 'Kuta Utara', 'Mengwi', 'Abiansemal', 'Petang'],
  },
  'Kalimantan Barat': {
    'Kota Pontianak': ['Pontianak Kota', 'Pontianak Barat', 'Pontianak Selatan', 'Pontianak Tenggara', 'Pontianak Timur', 'Pontianak Utara'],
  },
  'Kalimantan Selatan': {
    'Kota Banjarmasin': ['Banjarmasin Tengah', 'Banjarmasin Barat', 'Banjarmasin Timur', 'Banjarmasin Selatan', 'Banjarmasin Utara'],
    'Kota Banjarbaru': ['Banjarbaru Utara', 'Banjarbaru Selatan', 'Landasan Ulin', 'Cempaka', 'Liang Anggang'],
  },
  'Kalimantan Timur': {
    'Kota Samarinda': ['Samarinda Kota', 'Samarinda Ulu', 'Samarinda Ilir', 'Samarinda Seberang', 'Samarinda Utara', 'Sungai Kunjang'],
    'Kota Balikpapan': ['Balikpapan Kota', 'Balikpapan Selatan', 'Balikpapan Tengah', 'Balikpapan Utara', 'Balikpapan Barat', 'Balikpapan Timur'],
  },
  'Sulawesi Selatan': {
    'Kota Makassar': ['Ujung Pandang', 'Makassar', 'Mariso', 'Mamajang', 'Bontoala', 'Wajo', 'Tallo', 'Ujung Tanah', 'Panakkukang', 'Tamalate', 'Biringkanaya', 'Manggala', 'Rappocini', 'Tamalanrea'],
  },
}
